### PR TITLE
removed TemplateResponseMixin (and template) from SignatureCallbackView

### PR DESCRIPTION
**Pull request by smcoll**
proposed fix for #53

### CODE REVIEW

**Comment by zebuline** [comment]
@smcoll can you rebase this PR, for the CI ?

**Comment by smcoll** [comment]
@zebuline done, but it looks like some keys are missing for CI

**Comment by zebuline** [comment]
#62 should fix encrypted vars issue for travis. Can you rebase again ?

**Comment by smcoll** [comment]
@zebuline it doesn't look like that resolved it

**Comment by zebuline** [comment]
@smcoll there is some errors (real errors :) ): https://travis-ci.org/novafloss/django-docusign/builds/146654583

``AttributeError: 'SignatureCallbackView' object has no attribute 'render_to_response'``

**Comment by smcoll** [comment]
@zebuline you're right.  i think i resolved that, but i'm still seeing authentication errors in the build.

**Comment by zebuline** [comment]
@smcoll Yes, it is a feature :/
Travis does not send encrypted vars to "untrusted" builds (PR from forks). I have to fetch your branch in this repo (https://github.com/novafloss/django-docusign/tree/53-remove-templateresponsemixin); it will relaunch the build "push".

**Comment by zebuline** [comment]
Yeah, the build passed !
Thx @smcoll for your work.

**Pull request merged**
