### PR TITLE
support Django 1.7, 1.8 in tox.ini and setup.py

### PR DESCRIPTION
**Pull request by smcoll**
Added Django 1.8 to tox config, allowing Django 1.8 for setup.py install. #40, #41

i believe that #42 with it's 1.7 support also handles 1.8 support adequately.

### CODE REVIEW

**Comment by smcoll** [comment]
Best i can tell, the tests are failing due to a missing key in CI?

**Comment by k4nar** [comment]
Indeed.

@bersace : Any idea ? I see some secrets in the `.travis.yml`, maybe they need to be updated ?

**Comment by bersace** [comment]
This is a nice case where integration tests are a wrong idea in a library project, instead of just unit tests. :-1: 

Yes, django-docusign tests requires a specific setup in docusign testbed.

:fr:  @k4nar as-tu accès aux paramètres travis ? Il y a une doc dans RH2 qui explique comment créer une compte docusign. Essaie de t'en sortir. Sinon, on en discute en visio ou sur IRC :-)

**Comment by smcoll** [comment]
any update here?

**Comment by zebuline** [comment]
@smcoll I propose to close this PR in favor of #61

**Comment by smcoll** [comment]
@zebuline sounds fine to me

**Pull request closed without merging**
